### ISSUE TITLE
No gallery specified.

### ISSUE THREAD

**Issue by bahari15** [ZerataX/unlimted_favorites#2]
After exhentai huge updates few days ago it's causing the userscript to stop working properly, when I tried to add a gallery to my Favorites it returned a "No gallery specified." message with a blank white background... Can you please look into this, thanks.
![unlimited favs error](https://user-images.githubusercontent.com/36342630/36066504-3e9674b8-0edd-11e8-8aca-94fa4acad73d.png)

**Comment by zeratax** [comment]
Oh yeah you're right. I will asap look into this will probably take me a few days though sadly.
probably should clean this up anyways. thanks for the report.

**Comment by Yoposoc** [comment]
Still getting this error.

**Comment by zeratax** [comment]
The bug itself should know be fixed. Sorry for the delay.
Design is still inconsistent and I haven't heavily tested it.
Will revamp a lot of the code and hopefully fix anything else in the coming days.
