### ISSUE TITLE
Cannot load next page in a custom favlist

### ISSUE THREAD

**Issue by Yoposoc** [ZerataX/unlimted_favorites#4]
I would say this is high priority.

https://z.zz.ht/Uqr09.gif

see the gif for the behavior. When I go to page 2, it looks like I've edited the video to make it look like it skips, but that's just because waterfox is a bitch and it's lagging. Basically, it shows me for a few seconds of the second page for my first real favlist (it's "Lolis" for me) but then shows me nothing. Not sure why it says "false" in that text box too.
Log: 
![image](https://user-images.githubusercontent.com/2718371/84112464-a8052f00-a9dd-11ea-9b06-f259ce38fd62.png)

**Comment by zeratax** [comment]
oh that was a weird regression should be fixed again
