### ISSUE TITLE
Re-categorizing a gallery from a custom to true favlist overwrites favorite notes for all custom favlist items

### ISSUE THREAD

**Issue by Yoposoc** [ZerataX/unlimted_favorites#5]
Strange bug, I guess this is medium-low priority? It's more cosmetic/confusing than anything. I am not sure if it impacts the search features since it's broken (separate issue).

I found a gallery in my `Backlog #1` custom favlist that I want to change to my `Lolis` favlist.
![waterfox_2020-06-08_23-16-38](https://user-images.githubusercontent.com/2718371/84113966-6629b800-a9e0-11ea-9cd9-b82bf4e5d207.jpg)
![waterfox_2020-06-08_23-16-14](https://user-images.githubusercontent.com/2718371/84114017-76da2e00-a9e0-11ea-8ef1-39c681d4a8b0.jpg)
The notes don't show up.
![waterfox_2020-06-08_23-16-22](https://user-images.githubusercontent.com/2718371/84114034-7e013c00-a9e0-11ea-8d7d-775fae83fe16.jpg)
I've changed it. I have a [different userscript](https://sleazyfork.org/en/scripts/8280-e-h-auto-note-favourites) that automatically fills in the notes section with the gallery tags when I choose a new favlist. It did that to populate the notes section.
![waterfox_2020-06-08_23-23-25](https://user-images.githubusercontent.com/2718371/84114049-83f71d00-a9e0-11ea-9af3-bece1887c191.jpg)

That gallery is successfully in my `Lolis` favlist now but a weird bug has occured for the galleries still in my `Backlog #1` custom favelist. Strange.
![2020-06-08_23-35-40](https://user-images.githubusercontent.com/2718371/84114205-cf113000-a9e0-11ea-86bb-4bdbfc454e52.jpg)

I can confirm that it's changed to that in all the other favlists too. I repeated it with a different gallery.
![waterfox_2020-06-08_23-26-11](https://user-images.githubusercontent.com/2718371/84114341-0d0e5400-a9e1-11ea-84ad-48a51177b8b8.jpg)
Switched this from `Backlog #1` to `Lolis`. This is the log, and it looks normal?
![image](https://user-images.githubusercontent.com/2718371/84114691-a89fc480-a9e1-11ea-97bf-9b498f2a62a6.png)

Then I went to `Things to translate`
![waterfox_2020-06-08_23-29-51](https://user-images.githubusercontent.com/2718371/84114403-28795f00-a9e1-11ea-933d-5db7c34a464f.jpg)
This is the log.
![image](https://user-images.githubusercontent.com/2718371/84114735-b9503a80-a9e1-11ea-9bad-5099005b4a82.png)

**Comment by ZerataX** [comment]
Yeah I was just lazy and haven't yet added all the namespace aliases, or rather i only added the aliases.
so `female` is just `f` and artist is missing. I have that fixed in a minute

**Comment by zeratax** [comment]
ah yeah I don't use notes so I haven't yet done anything with that yet. this should be entirely visual. it just copies the first gallery html item and then modifies it. and since I didn't have notes on that I never thought to replace them when copying them.

**Comment by zeratax** [comment]
should be fixed with 3cfb06d
