### ISSUE TITLE
Searching custom favlist galleries is partially broken

### ISSUE THREAD

**Issue by Yoposoc** [ZerataX/unlimted_favorites#6]
I would say this is high priority. Without being able to search, it'll be real hard going through these lists.

I'm going to target this gallery as a search result with searching `artist:"land sale"`. it is in `Backlog C89+`
![image](https://user-images.githubusercontent.com/2718371/84114863-ed2b6000-a9e1-11ea-93ad-367df7a8b984.png)

![image](https://user-images.githubusercontent.com/2718371/84115040-3a0f3680-a9e2-11ea-8c1c-9e9527808de7.png)
I get no hits
![image](https://user-images.githubusercontent.com/2718371/84115149-6c209880-a9e2-11ea-8045-e5cecf721205.png)

I'll try again after I go into the favlist itself. It's the third entry.
![image](https://user-images.githubusercontent.com/2718371/84115229-8f4b4800-a9e2-11ea-84d4-8b88cd3f1281.png)

I guess for the custom favlists, it's a instant search text box? It's neat, and it worked
![image](https://user-images.githubusercontent.com/2718371/84115407-e3eec300-a9e2-11ea-8bd8-bc8bff19f08d.png)
But it shows a whole lot of other results, of which I have no idea why it came up. Many of them don't even have the words `land` or `sale`.

I used a extremely specific search term, romaji from the title. That worked.
![image](https://user-images.githubusercontent.com/2718371/84115547-18627f00-a9e3-11ea-8310-c92ea0f18f64.png)

In actuality though, I would probably search with tags. That worked too. Maybe it has issues with the search term `artist:`?

I would love to be able to search within multiple categories though. Is that possible?

**Comment by Yoposoc** [comment]
This is a pretty big issue: searching for gendered tags is totally broken:
![image](https://user-images.githubusercontent.com/2718371/84116798-5bbded00-a9e5-11ea-8b1d-5abcb9d756be.png)

**Comment by Yoposoc** [comment]
Another thing is that this immediate response search function is actually really slow. My browser will hang for a couple of seconds until what I typed shows up. I'm not sure if it's just me. I would rather have the "normal" search where I type and then press search.

**Comment by zeratax** [comment]
Yeah I was just lazy and haven't yet added all the namespace aliases, or rather i only added the aliases.
so `female` is just `f` and artist is missing. I have that fixed in a minute.
somewhat surprised that `artist:` does anything at all, it should just fail

I wasn't sure how intensive the search would be, since it's instant on my pc, but sure I can change that behavior, or make it optional

Multiple categories is kinda broken where it will just combine every result for each category it matches. not that hard to fix, but probably not today.

**Comment by zeratax** [comment]
So should now support all namespaces and only searches when you click outside of the search input, will later do a button and enter

**Comment by zeratax** [comment]
Yeah I think search should now work properly. 

Edit: oh and global search still doesn't work, since it's not easy to find out what your favs are. I could do a global search for default and unlimited lists, but probably not both at the same time

**Comment by Yoposoc** [comment]
> so female is just f and artist is missing. 

ah ok, I forgot you said that. Sorry and thank you.
