### ISSUE TITLE
Cannot import favs in a new machine

### ISSUE THREAD

**Issue by Yoposoc** [ZerataX/unlimted_favorites#9]
I'm on a new computer, and I'm trying to import my favs jsons.

![image](https://user-images.githubusercontent.com/2718371/103158938-48535300-4778-11eb-9a87-6f9bac7c40b3.png)
I keep getting this every time, even though I'm already on 1.0.1. And my favs won't update. What gives?

**Comment by zeratax** [comment]
huh if you open that json file and search for `version` what do you get?

also anything interesting in the dev console? (ctrl shift I)

**Comment by zeratax** [comment]
I guess it's also somewhat nonsensical to backup if you're importing a backup, but not sure why it does not import

**Comment by Yoposoc** [comment]
Ok, a few things.
1. This explains why I got nothing: 
![image](https://user-images.githubusercontent.com/2718371/103166217-b6c5fe80-47d4-11eb-9462-5ed72506a321.png)

2. thankfully I had a backup. I might have lost a few things but I'm glad I can at least revert to sometime instead of losing everything. when I searched `version` I only get it in a title of a gallery. 
![image](https://user-images.githubusercontent.com/2718371/103166264-30f68300-47d5-11eb-89df-3a34fe309fa3.png) 

3. Importing worked this time, although I still get the popup. Not sure how my console can help but here you go.

**Comment by zeratax** [comment]
hmm well depending on how old the backup is it might not have had the `version` tag and everytime your list gets updated (e.g. that tag gets added) it will ask to backup.

so I am unsure if something is bugged. It's definitely weird that your initial backup is empty.

**Comment by Yoposoc** [comment]
oops, I didn't upload a pic of my console. Eh, do you still want it? It did not seem helpful.

**Comment by zeratax** [comment]
nah probably not.
if you only got the popup once I consider this fixed.
I guess I'll try to remove the popup from importing, but other than that I don't have much to go on regarding the empty backup.
